server:
  port: 8086

security:
  internal:
    token: Ylc5bGVFRndhUzFwYm5SbGNtNWhiQzFyWlhrPQ==

integration:
  rest:
    iss-moex-url: "https://iss.moex.com/iss"
    auth-service-url: http://localhost:8081