server:
  port: 8086

integration:
  rest:
    iss-moex-url: "https://iss.moex.com/iss"
    auth-service-url: http://localhost:8081

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        exclude: '*'
  zipkin:
    tracing:
      endpoint: http://103.249.132.74:9411/api/v2/spans
    auth-service-url: http://localhost:8081